##端口号
server:
  servlet:
    context-path: /

##数据源设置
spring:
  datasource:
    type: com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    template-loader-path: classpath:/views/

##mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.mage.dgj.vo;com.mage.dgj.query;com.mage.dgj.dto
  configuration:
    map-underscore-to-camel-case: true

##pageHelper
pagehelper:
  helper-dialect: mysql

